2019-04-11 00:40:09  main.py Line:52 - INFO - This is the password text 
2019-04-11 02:29:27  main.py Line:52 - INFO - This is the password text dsdsd
2019-04-11 02:29:27  main.py Line:68 - DEBUG - HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f03d39752e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-04-11 02:44:01  main.py Line:51 - INFO - This is the password text 12
2019-04-11 02:44:22  main.py Line:51 - INFO - This is the password text 12
2019-04-11 02:45:15  main.py Line:51 - INFO - This is the password text 12
2019-04-11 02:45:45  main.py Line:51 - INFO - This is the password text 12345678
2019-04-11 02:47:36  main.py Line:51 - INFO - This is the password text 12345678
2019-04-11 02:48:06  main.py Line:51 - INFO - This is the password text 12345678
2019-04-11 02:56:42  main.py Line:51 - INFO - This is the password text 12345678
